ALTER TABLE users DROP COLUMN name;
ALTER TABLE users DROP COLUMN updated_at;
ALTER TABLE users ADD COLUMN password_hash VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE users ALTER COLUMN password_hash DROP DEFAULT;